# Generated by Django 4.2.14 on 2024-08-03 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_manager_alter_user_role_task_notes_dailycheckin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycheckin',
            name='time_of_checkin',
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='datetime_of_checkin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
